export const authorPosition: string[] = [
  '1er Autor',
  '2do Autor',
  '3er Autor',
  '4to Autor',
  '5to Autor en adelante',
];

export const porpouse: string[] = [
  'Asimilación de Tecnología',
  'Creación',
  'Desarrollo Tecnológico',
  'Difusión',
  'Generación de Conocimiento',
  'Investigación Aplicada',
  'Transferencia de Tecnología',
];

export const articleState: string[] = ['Sometido', 'Aceptado', 'Publicado'];

export const impiClass: string[] = [
  'A - Necesidades Corrientes de la Vida',
  'B - Técnicas Industriales Diversas; Transportes',
  'C - Química; Metalurgia',
  'D - Textiles; Papel',
  'E - Construcciones Fijas',
  'F - Mecánica; Iluminación; Calefacción; Armamento; Voladura',
  'G - Física',
  'H - Electrónica',
];

export const sector: string[] = [
  'Administración',
  'Alimentos',
  'Manufactura',
  'Medio Ambiente',
  'Pedagogía',
  'Tecnologías de la Información y Comunicaciones',
];

export const subSectorAdmin: string[] = [
  'Administración',
  'Administración industrial',
  'Ciencías económicas',
  'Ciencías socíales',
  'Contador Público',
  'Contaduría',
  'Derecho',
  'Desarrollo comunitario',
  'Gestión empresarial',
  'Ingeniería Administrativa',
  'Planeación estratégica',
];

export const subSectorAlimento: string[] = [
  'Acuacultura',
  'Agricultura',
  'Agropecuaria',
  'Agrosistemas',
  'Biología',
  'Bioquímica',
  'Biotecnología',
  'Biotecnología microbiana',
  'Irrigación',
  'Pesquería',
  'Producción pecuaria',
];

export const subSectorManu: string[] = [
  'Aeronáutica',
  'Automatización',
  'Eléctrica',
  'Electrónica',
  'Industrial',
  'Instrumentación biomédica',
  'Materiales',
  'Mecánica',
  'Mecatrónica',
  'Metalurgia',
  'Procesamiento de señales',
  'Química',
  'Robótica',
];

export const subSectorMedioAmb: string[] = [
  'Agua',
  'Arquitectura sostenible y gestión urbana',
  'Bioprocesos',
  'Desarrollo forestal',
  'Eficiencia energética',
  'Energías renovables',
  'Gestión ambiental',
  'Manejo de zona costera',
  'Procesos Químicos',
  'Suelo',
  'Urbanismo',
];

export const subSectorPeda: string[] = [
  'Educación',
  'Enseñanza de Matematicas',
  'Enseñanza de Ciencias',
  'Filosofía',
  'Historia',
  'Letras',
  'Lingüistica',
  'Política educativa',
];

export const subSectorTecInfo: string[] = [
  'Bases de datos',
  'Computación',
  'Desarrollo Web',
  'Minería de datos',
  'Multimedia',
  'Programación aplicada a la tecnología',
  'Redes',
  'Sistemas computacionales',
  'Software',
  'Tecnologías de la información para el aprendizaje',
];

export const priority: string[] = [
  'Salud',
  'Química',
  'Mecánica',
  'Eléctrica',
  'Bioquímica',
  'Computación',
  'Agropecuarias',
  'Administración',
];

export const acknowledgement: string[] = [
  'Ciencias Agrícolas y Forestales',
  'Ciencias Biológicas',
  'Ciencias de la Computación, Sistemas Computacionales, Informática',
  'Ciencias de la Educación',
  'Ciencias de la Tierra y el Medio Ambiente',
  'Ciencias de los Materiales, Polímeros',
  'Ciencias del Mar',
  'Ciancias Químicas',
  'Ingeniería Eléctrica, Electrónica',
  'Ingeniería Industrial, Administrativa y Desarrollo Regional',
  'Ingeniería Mecánica, Mecatrónica',
  'Ingeniería Química, Bioquímica, Alimentos, Biotecnológia',
];

export const projectTypeArticulo: string[] = [
  'Divulgación',
  'Arbitrado',
  'Indexado',
];

export const projectTypePrototipo: string[] = [
  'Arquitectónico',
  'Programa de Cómputo',
  'Diseño Industrial',
  'Desarrollo Industrial',
];

export const projectTypeAutoral: string[] = [
  'Arquitectónica',
  'Arte aplicado',
  'Audiovisual',
  'Base de datos',
  'Caricatura',
  'Cinematográfica',
  'Danza',
  'De carácter plástico',
  'Dibujo',
  'Dramática',
  'Escultórica',
  'Fotográfica',
  'Historieta',
  'Literaria',
  'Música con letra',
  'Música sin letra',
  'Pictórica',
  'Programa de cómputo',
  'Programa de radio',
  'Programa de televisión',
];

export const projectTypeIMPI: string[] = [
  'Denominación de Origen',
  'Marca',
  'Modelo de Utilidad',
  'Patente',
];

export const countries: string[] = [
  'Afganistán',
  'Albania',
  'Alemania',
  'Andorra',
  'Angola',
  'Antigua y Barbuda',
  'Arabia Saudita',
  'Argelia',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaiyán',
  'Bahamas',
  'Bangladés',
  'Barbados',
  'Baréin',
  'Bélgica',
  'Belice',
  'Benín',
  'Bielorrusia',
  'Birmania',
  'Bolivia',
  'Bosnia y Herzegovina',
  'Botsuana',
  'Brasil',
  'Brunéi',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Bután',
  'Cabo Verde',
  'Camboya',
  'Camerún',
  'Canadá',
  'Catar',
  'Chad',
  'Chile',
  'China',
  'Chipre',
  'Ciudad del Vaticano',
  'Colombia',
  'Comoras',
  'Corea del Norte',
  'Corea del Sur',
  'Costa de Marfil',
  'Costa Rica',
  'Croacia',
  'Cuba',
  'Dinamarca',
  'Dominica',
  'Ecuador',
  'Egipto',
  'El Salvador',
  'Emiratos Árabes Unidos',
  'Eritrea',
  'Eslovaquia',
  'Eslovenia',
  'España',
  'Estados Unidos',
  'Estonia',
  'Etiopía',
  'Filipinas',
  'Finlandia',
  'Fiyi',
  'Francia',
  'Gabón',
  'Gambia',
  'Georgia',
  'Ghana',
  'Granada',
  'Grecia',
  'Guatemala',
  'Guyana',
  'Guinea',
  'Guinea ecuatorial',
  'Guinea-Bisáu',
  'Haití',
  'Honduras',
  'Hungría',
  'India',
  'Indonesia',
  'Irak',
  'Irán',
  'Irlanda',
  'Islandia',
  'Islas Marshall',
  'Islas Salomón',
  'Israel',
  'Italia',
  'Jamaica',
  'Japón',
  'Jordania',
  'Kazajistán',
  'Kenia',
  'Kirguistán',
  'Kiribati',
  'Kuwait',
  'Laos',
  'Lesoto',
  'Letonia',
  'Líbano',
  'Liberia',
  'Libia',
  'Liechtenstein',
  'Lituania',
  'Luxemburgo',
  'Madagascar',
  'Malasia',
  'Malaui',
  'Maldivas',
  'Malí',
  'Malta',
  'Marruecos',
  'Mauricio',
  'Mauritania',
  'México',
  'Micronesia',
  'Moldavia',
  'Mónaco',
  'Mongolia',
  'Montenegro',
  'Mozambique',
  'Namibia',
  'Nauru',
  'Nepal',
  'Nicaragua',
  'Níger',
  'Nigeria',
  'Noruega',
  'Nueva Zelanda',
  'Omán',
  'Países Bajos',
  'Pakistán',
  'Palaos',
  'Palestina',
  'Panamá',
  'Papúa Nueva Guinea',
  'Paraguay',
  'Perú',
  'Polonia',
  'Portugal',
  'Reino Unido',
  'República Centroafricana',
  'República Checa',
  'República de Macedonia',
  'República del Congo',
  'República Democrática del Congo',
  'República Dominicana',
  'República Sudafricana',
  'Ruanda',
  'Rumanía',
  'Rusia',
  'Samoa',
  'San Cristóbal y Nieves',
  'San Marino',
  'San Vicente y las Granadinas',
  'Santa Lucía',
  'Santo Tomé y Príncipe',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leona',
  'Singapur',
  'Siria',
  'Somalia',
  'Sri Lanka',
  'Suazilandia',
  'Sudán',
  'Sudán del Sur',
  'Suecia',
  'Suiza',
  'Surinam',
  'Tailandia',
  'Tanzania',
  'Tayikistán',
  'Timor Oriental',
  'Togo',
  'Tonga',
  'Trinidad y Tobago',
  'Túnez',
  'Turkmenistán',
  'Turquía',
  'Tuvalu',
  'Ucrania',
  'Uganda',
  'Uruguay',
  'Uzbekistán',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Yibuti',
  'Zambia',
  'Zimbabue',
];
